#!/usr/bin/env python3
seq1='------------------------------------------------------------ -------------------------AGCACCCTCCCACCTCATCCCACCCTTCTGATCTC AATCCAACGTCGCATCTCCACCGTCTCGC-----GGATCGACCCAGCGAAGTCC----CT CCCGCCCCCAAAGTCCC----------CCAAATCTTGCAGTTCCCTCCTAAATCCTCCCC ATATAAACCAACCCCCCGCCCTCAGATCCCTAATC-CCATCGCA--AGCATCAGACTCCC TCCAAAGCAGGCAGCAGCTCCTCTTCTTCCTAATCACACTATCTCGGAGAGGAGCGGCCA TGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAGGGCGGCGCCAAGCGGCACCGGA AGGTCCTCCGCGACAACATCCAGGGCATCACCAAGCCGGCGATCCGGAGGCTGGCCAGGA GGGGCGGCGTGAAGCGCATCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGA TCTTCCTCGAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAAAA CCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGGCCGCACCCTCTACGGCT TCGGAGGCTAGATTTGTGTGGTGAAGCAACTTCCTCGTTTGCTCTGTGATCTGTGCTGTC GTAGATGAGATTTACTGATTTGGCGTGCGCC---GGTTGTATTCTGTCATGGGGTTCAGT GGGCTGTGTAATACCTTGCTCTGTACTTCTGTTCAA----TGCAATCACTTCTATTC--- ----------------TGAA-----------------'
seq2='TCTAGAGATGGCGCCATTTGATTCCAGCAGCCACAAAGCACTAGAACAATCGATGCTAAG AGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGGAATGCAGCGGTGGTCAGCCT AAAACACTGTAGAAGGGCAAGATGAGCTGAGTAATTTTTAACTGGGCATCATTTTTAGAA ACTGGAGTTTAAGTACCCCCTTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGCAAGGT CTGTGAATCGGCCGACCGGATGCAGCTGGTGTGGAGAGTTCCCAATCAGGTCCGATTTAT TACTATATAAAGTACTGCTGC--GAGGCTTGCCGTGTTGCATTTTGTTTAGTACAAGACA TGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAAGGAGGCGCTAAGCGCCACCGCA AAGTTCTGCGCGACAACATTCAGGGCATCACCAAGCCCGCCATCCGACGCCTGGCACGGC GTGGAGGCGTTAAGCGCATCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAG TGTTTTTGGAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAAGA CAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCACCCTGTATGGCT TTGGCGGCTGAGTGTTTTACTTACTTACACGGTTCCTCAAAGGCCCTTCTCAGGGCCACC CATGAAGTCTGTGAAAGAGCTGTAGACTAAAGATAGTTAATTTCTTAAGAAC-----ACT TAAACGTATGGCAGTTTTGGCAAATTAGCGATTCCACATAAGCAGTCGCTGAAGTTTGAG GTTCGGTGCCCCTTTCAGCATTACTTAGTGGTTAAAA'
seq1=seq1.replace(' ','')
seq2=seq2.replace(' ','')
identity=0

for n in range(len(seq1)):
    if seq1[n]==seq2[n]:
        identity+=1

seq1A=seq1.replace('-','')

print(f'Percentage identity of these 2 sequences is: {(identity/(len(seq1A)-7)):.2%}')
